name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour à v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Mise à jour à v3
        with:
          node-version: '20'  # Mise à jour à Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Mise à jour à v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour à v3

      - name: Download artifact
        uses: actions/download-artifact@v3  # Mise à jour à v3
        with:
          name: build
          path: build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Mise à jour vers le dossier de build correct
